### ISSUE TITLE
add minimum_length to forward a video

### ISSUE THREAD

**Issue by sunilroyy007** [AbirHasan2005/Forward-Client#12]
there is some videos which have 2 to 5 minutes duration and have 1GB size and it autoforwards those. can you add minimum length

**Comment by AbirHasan2005** [comment]
Okay, SOON!

**Comment by AbirHasan2005** [comment]
> there is some videos which have 2 to 5 minutes duration and have 1GB size and it autoforwards those. can you add minimum length

`MINIMUM_FILE_SIZE` set this in configs. Value in bytes.

**Comment by sunilroyy007** [comment]
> > there is some videos which have 2 to 5 minutes duration and have 1GB size and it autoforwards those. can you add minimum length
> 
> `MINIMUM_FILE_SIZE` set this in configs. Value in bytes.

that is file size bro i asked for video length

**Comment by AbirHasan2005** [comment]
It will work for videos as well.

**Comment by sunilroyy007** [comment]
you are not getting what i am saying 😑

here is an example

i have a file with 5 minutes and 1GB size... if i keep 1GB minimum size limit ,it will transfer that 5 minutes video and 20 minutes video which has 1GB size

what i am saying is add minimum length option so if i keep 20 minutes minimum length it wont transfer that 5 minutes video and only transfer above 20 minutes duration videos only

**Comment by AbirHasan2005** [comment]
Oh, you mean video duration length 😂

Okay, I will add soon.
