### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Venomhash123** [AbirHasan2005/Forward-Client#16]
Maine ek tg account create kiya abhi 
Uska pyrogram string create krke bot vars m daala to ye error aa rhi h
Maine kai baar string season bna liye 
Lekin sbhi m ye problem aa rhi 
But old tg account m ye problem nhi aa rhi only new account m aa rhi h
![Screenshot_2022-01-17-20-58-07-829_com android chrome](https://user-images.githubusercontent.com/89146099/149798633-cfbf8f90-b2ba-4372-a869-6d48d2d62697.jpg)

**Comment by Venomhash123** [comment]
Koi solution h sir eska

**Comment by Venomhash123** [comment]
Solved

**Comment by Master-Mind-007** [comment]
> Solved

Can you please explain how u solved the error. Because I am also experiencing same error.
