### ISSUE TITLE
int() argument must be a string

### ISSUE THREAD

**Issue by vladios13** [AbirHasan2005/Forward-Client#7]
When [configuring configs.py](https://github.com/AbirHasan2005/Forward-Client/blob/main/configs.py#L9), and running main.py I get the following error: 
![file_ #90](https://user-images.githubusercontent.com/10531221/125901088-9bf33e51-b617-47eb-86e2-88bed8b02264.png)

However, if you fix this line like this:  `API_ID = int(os.environ.get("APP_ID", 996380))`
You will get another error on startup: `ValueError: Unknown storage engine`
![file_ #91](https://user-images.githubusercontent.com/10531221/125902606-85923723-f1b0-4110-a6bb-0287f49692f5.png)

**Distributor ID:** Ubuntu
**Release:**        20.04
**Python:** 3.8.10

**Comment by AbirHasan2005** [comment]
`session_name` will be Authorized Telegram User Client's Session String. Use [@StringSessionGen_Bot](https://t.me/StringSessionGen_Bot) for that.

**Comment by vladios13** [comment]
`session_name` is prescribed as it is. The `config` itself is already prepared and filled with the necessary data. 
Look at the second screenshot, when I run `main.py`.

**Comment by AbirHasan2005** [comment]
Session String not recognized as Session. Maybe you done that same API_ID value problem.

**Comment by vladios13** [comment]
> Session String not recognized as Session. Maybe you done that same API_ID value problem.

Um, okay. Please tell me what to do, how to fill in the `app_id` correctly (if you look at the first screenshot and the first paragraph)?

Because filling app_id I get an error. Thank you!

**Comment by AbirHasan2005** [comment]
Check this: https://t.me/AbirHasan2005/94

**Comment by vladios13** [comment]
> Check this: https://t.me/AbirHasan2005/94

**Thank you very much**, but right now it is more important to run on your machine and not use heroku.

**Comment by AbirHasan2005** [comment]
Directly set like
```
API_ID = 1234...
API_HASH = "abcd123..."
```

**Comment by vladios13** [comment]
> Directly set like
> 
> ```
> API_ID = 1234...
> API_HASH = "abcd123..."
> ```

![image](https://user-images.githubusercontent.com/10531221/126448527-cd90aabe-032e-49e7-b846-993d5e45faaf.png)

Below is an example of how this is recorded. I still get an error. 

```
API_ID = int(os.environ.get(996380))
API_HASH = os.environ.get("311111111111111111111111111111")
```

**Comment by AbirHasan2005** [comment]
Not Like this!
```
API_ID = 996380
API_HASH = "311111111111111111111111111111"
```
